strings:
# SG110CX: 3 inverter × 9 MPPT × 2 strings
{% for inv_id in [1, 2, 3] %}
  {% for mppt_index in range(1, 10) %}
    {% for string_index in range(1, 3) %}
  - id: {{ inv_id }}{{ mppt_index }}{{ string_index }}
    inverter_id: {{ inv_id }}
    mppt_id: {{ inv_id }}{{ mppt_index }}
    string_index: {{ string_index }}
    V_string: 0.0
    I_string: 0.0
    P_string: 0.0
    Max_I: 15.0
    Max_V: 1100.0
    Max_P: 6100.0
    Max_P_string: 6100.0
    string_on_mppt: 2
    {% endfor %}
  {% endfor %}
{% endfor %}

# SG50CX: 1 inverter × 5 MPPT × 2 strings
{% for mppt_index in range(1, 6) %}
  {% for string_index in range(1, 3) %}
  - id: 4{{ mppt_index }}{{ string_index }}
    inverter_id: 4
    mppt_id: 4{{ mppt_index }}
    string_index: {{ string_index }}
    V_string: 0.0
    I_string: 0.0
    P_string: 0.0
    Max_I: 15.0
    Max_V: 1100.0
    Max_P: 6100.0
    Max_P_string: 6100.0
    string_on_mppt: 2
  {% endfor %}
{% endfor %}

